[package]
name = "duckdb_conn"
version = "0.1.0"
edition = "2021"

[dependencies]
common_core = {path = "../common_core"}
common_conn = {path = "../common_conn"}
duckdb = { version = "1.3.0", features = ["bundled"] }