[package]
name = "scylla_conn"
version = "0.1.0"
edition = "2021"

[dependencies]
common_core = {path = "../common_core"}
common_conn = {path = "../common_conn"}
tokio = {version = "1.43.0"}
scylla = "0.15.1"


[[test]]
name = "test_scylla_conn"
path = "tests/mod.rs"